name: sequential-jobs
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get git code
        uses: actions/checkout@v3
      - name: Run a script
        run: sudo bash ${GITHUB_WORKSPACE}/sys_info_1.sh
      - name: End-Workflow
        run: echo "Execution is completed"  
  second-job:
    needs: first-job	
    runs-on: ubuntu-latest
    steps:
      - name: Install nginx
        run: | 
          sudo apt update
          sudo apt install nginx
          sudo ufw app list
          sudo ufw allow 'Nginx HTTP'
          sudo systemctl restart nginx
          sudo systemctl status nginx
      - name: End-Workflow
        run: echo "Execution is completed"      