name: Expressions
on: workflow_dispatch
jobs:
  expressions-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo GitHub context
        run: echo "${{ toJson(github) }}"
      - name: Echo Github Repo
        run: echo "${{ toJson(github.repository) }}"
      - name: Echo runner context
        run: echo "${{ toJson(runner) }}"
      - name: Echo strategy context
        run: echo "${{ toJson(strategy) }}"
      - name: Echo secrets context
        run: echo "${{ toJson(secrets) }}"