name: demo_vars
on: workflow_dispatch
env:
  AWS_ACCESS_KEY_ID: ${{vars.AWS_ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{vars.AWS_SECRET_KEY}}
  AWS_REGION: ${{vars.AWS_REGION}}
jobs:
  vars-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install terraform
        run: |
         wget  https://releases.hashicorp.com/terraform/${{vars.TFVERSION}}/terraform_${{vars.TFVERSION}}_linux_amd64.zip
         sudo unzip -o terraform_${{vars.TFVERSION}}_linux_amd64.zip -d /usr/local/bin
         terraform -version
      - name: Display AWS creds
        run: |
          echo "${{ env.AWS_REGION}}"
          echo "${{ env.AWS_ACCESS_KEY_ID}}"
          echo "${{ env.AWS_SECRET_ACCESS_KEY}}"
      - name: Validate input
        run: env
      - name: End-Workflow
        run: echo "Execution is completed" 