name: special-condtions
on: workflow_dispatch
jobs:
  condtional-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Run a script
        id: publish
        run: |
          sudo bash ${GITHUB_WORKSPACE}/sys_info_1.wsh > report.html
      - name: Alternate script
        if: failure()
        run: | 
          sudo bash ${GITHUB_WORKSPACE}/system_info.sh > report.txt
          sudo cat report.txt
      - name: Deploy nginx
        run: | 
          sudo apt install nginx
          sudo systemctl restart nginx
          sudo ls /var/www/html
      - name: Modify index file
        run: |
          sudo cat report.html 
          sudo cp -f report.html /var/www/html/index.html 
          sudo ls /var/www/html
          sudo cat /var/www/html/index.html
      - name: End-Workflow
        if: success()
        run: echo "Execution is completed without any errors"   
      - name: End-Workflow
        if: failure()
        run: echo "Execution is completed with errors"   
      - name: End-Workflow
        if: cancelled()
        run: echo "Execution is interrupted"   