name: Script Injection
on:
  issues:
    types:
      - opened
jobs:
  script-inject:
    runs-on: ubuntu-latest
    steps:
      - name: Validate issue
        run: |
          issue_title="${{ github.event.issue.title }}"
          if [[ "$issue_title" == *"bug"* ]]; then
          echo "Issue is about a bug!"
          else
          echo "Issue is not about a bug"
          fi