name: Script Injection solved
on:
  issues:
    types:
      - opened
jobs:
  script-inject:
    runs-on: ubuntu-latest
    steps:
      - name: Validate issue
        env:
          TITLE: ${{ github.event.issue.title }}
        run: |
          if [[ "$TITLE" == *"bug"* ]]; then
          echo "Issue is about a bug!"
          else
          echo "Issue is not about a bug"
          fi